// <auto-generated />
namespace Go2MusicStore.Platform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMigrationProjectNameGo2MusicStorePlatform : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMigrationProjectNameGo2MusicStorePlatform));
        
        string IMigrationMetadata.Id
        {
            get { return "201612131348545_Add-Migration -ProjectName Go2MusicStore.Platform"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
