// <auto-generated />
namespace Go2MusicStore.Platform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class creditcard_cardNumber_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creditcard_cardNumber_required));
        
        string IMigrationMetadata.Id
        {
            get { return "201612151605464_creditcard_cardNumber_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
