// <auto-generated />
namespace Go2MusicStore.Platform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlbumAlbumArtistUrl_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlbumAlbumArtistUrl_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201612101910174_Album.AlbumArtistUrl_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
